-- Update all products with proper image URLs including query parameters
UPDATE products SET image_url = '/placeholder.svg?height=400&width=400' WHERE name = 'Jeans Sostenibles';
UPDATE products SET image_url = '/placeholder.svg?height=400&width=400' WHERE name = 'Auriculares Bambú Bluetooth';
UPDATE products SET image_url = '/placeholder.svg?height=400&width=400' WHERE name = 'Mouse Ecológico';
UPDATE products SET image_url = '/placeholder.svg?height=400&width=400' WHERE name = 'Teclado Solar';
UPDATE products SET image_url = '/placeholder.svg?height=400&width=400' WHERE name = 'Laptop Reacondicionada';
UPDATE products SET image_url = '/placeholder.svg?height=400&width=400' WHERE name = 'Tablet Renovada';
UPDATE products SET image_url = '/placeholder.svg?height=400&width=400' WHERE name = 'Smartphone Reacondicionado';
UPDATE products SET image_url = '/placeholder.svg?height=400&width=400' WHERE name = 'Champú Sólido Natural';
UPDATE products SET image_url = '/placeholder.svg?height=400&width=400' WHERE name = 'Sérum Vitamina C';
UPDATE products SET image_url = '/placeholder.svg?height=400&width=400' WHERE name = 'Aceite de Argán Orgánico';
UPDATE products SET image_url = '/placeholder.svg?height=400&width=400' WHERE name = 'Mascarilla Arcilla Verde';
UPDATE products SET image_url = '/placeholder.svg?height=400&width=400' WHERE name = 'Bálsamo Labial Vegano';
UPDATE products SET image_url = '/placeholder.svg?height=400&width=400' WHERE name = 'Desodorante Natural';
UPDATE products SET image_url = '/placeholder.svg?height=400&width=400' WHERE name = 'Miel Orgánica';
UPDATE products SET image_url = '/placeholder.svg?height=400&width=400' WHERE name = 'Quinoa Orgánica';
UPDATE products SET image_url = '/placeholder.svg?height=400&width=400' WHERE name = 'Aceite de Oliva Extra Virgen';
UPDATE products SET image_url = '/placeholder.svg?height=400&width=400' WHERE name = 'Almendras Orgánicas';
UPDATE products SET image_url = '/placeholder.svg?height=400&width=400' WHERE name = 'Cacao en Polvo Orgánico';
UPDATE products SET image_url = '/placeholder.svg?height=400&width=400' WHERE name = 'Pasta Integral Orgánica';
UPDATE products SET image_url = '/placeholder.svg?height=400&width=400' WHERE name = 'Té Verde Orgánico';
UPDATE products SET image_url = '/placeholder.svg?height=400&width=400' WHERE name = 'Cepillo de Bambú';
UPDATE products SET image_url = '/placeholder.svg?height=400&width=400' WHERE name = 'Bolsas Reutilizables';
UPDATE products SET image_url = '/placeholder.svg?height=400&width=400' WHERE name = 'Velas de Soja Natural';
UPDATE products SET image_url = '/placeholder.svg?height=400&width=400' WHERE name = 'Toallas de Bambú';
UPDATE products SET image_url = '/placeholder.svg?height=400&width=400' WHERE name = 'Macetas Recicladas';
UPDATE products SET image_url = '/placeholder.svg?height=400&width=400' WHERE name = 'Alfombra de Yute';
UPDATE products SET image_url = '/placeholder.svg?height=400&width=400' WHERE name = 'Cojines de Algodón Reciclado';
UPDATE products SET image_url = '/placeholder.svg?height=600&width=600' WHERE name = 'Camiseta Orgánica Básica';
UPDATE products SET image_url = '/placeholder.svg?height=400&width=400' WHERE name = 'Café Orgánico';
UPDATE products SET image_url = '/placeholder.svg?height=400&width=400' WHERE name = 'Jabón Biodegradable';
UPDATE products SET image_url = '/placeholder.svg?height=400&width=400' WHERE name = 'Vestido de Lino Natural';
UPDATE products SET image_url = '/placeholder.svg?height=400&width=400' WHERE name = 'Zapatillas Recicladas';
UPDATE products SET image_url = '/placeholder.svg?height=400&width=400' WHERE name = 'Bolso de Algodón Orgánico';
UPDATE products SET image_url = '/placeholder.svg?height=400&width=400' WHERE name = 'Bufanda Artesanal';
UPDATE products SET image_url = '/placeholder.svg?height=400&width=400' WHERE name = 'Sombrero de Paja Reciclada';
UPDATE products SET image_url = '/placeholder.svg?height=400&width=400' WHERE name = 'Cargador Solar Portátil';
UPDATE products SET image_url = '/placeholder.svg?height=400&width=400' WHERE name = 'Crema Facial Orgánica';
