-- Update all product images with real generated images
UPDATE products SET image_url = '/products/auriculares-bambu.jpg' WHERE name = 'Auriculares Bambú Bluetooth';
UPDATE products SET image_url = '/products/mouse-ecologico.jpg' WHERE name = 'Mouse Ecológico';
UPDATE products SET image_url = '/products/teclado-solar.jpg' WHERE name = 'Teclado Solar';
UPDATE products SET image_url = '/products/desodorante-natural.jpg' WHERE name = 'Desodorante Natural';
UPDATE products SET image_url = '/products/miel-organica.jpg' WHERE name = 'Miel Orgánica';
UPDATE products SET image_url = '/products/quinoa-organica.jpg' WHERE name = 'Quinoa Orgánica';
UPDATE products SET image_url = '/products/aceite-oliva.jpg' WHERE name = 'Aceite de Oliva Extra Virgen';
UPDATE products SET image_url = '/products/almendras-organicas.jpg' WHERE name = 'Almendras Orgánicas';
UPDATE products SET image_url = '/products/cacao-polvo.jpg' WHERE name = 'Cacao en Polvo Orgánico';
UPDATE products SET image_url = '/products/pasta-integral.jpg' WHERE name = 'Pasta Integral Orgánica';
UPDATE products SET image_url = '/products/te-verde.jpg' WHERE name = 'Té Verde Orgánico';
UPDATE products SET image_url = '/products/cepillo-bambu.jpg' WHERE name = 'Cepillo de Bambú';
UPDATE products SET image_url = '/products/velas-soja.jpg' WHERE name = 'Velas de Soja Natural';
UPDATE products SET image_url = '/products/toallas-bambu.jpg' WHERE name = 'Toallas de Bambú';
UPDATE products SET image_url = '/products/macetas-recicladas.jpg' WHERE name = 'Macetas Recicladas';
UPDATE products SET image_url = '/products/alfombra-yute.jpg' WHERE name = 'Alfombra de Yute';
UPDATE products SET image_url = '/products/cojines-algodon.jpg' WHERE name = 'Cojines de Algodón Reciclado';
UPDATE products SET image_url = '/products/cafe-organico.jpg' WHERE name = 'Café Orgánico';
UPDATE products SET image_url = '/products/jabon-biodegradable.jpg' WHERE name = 'Jabón Biodegradable';
UPDATE products SET image_url = '/products/vestido-lino.jpg' WHERE name = 'Vestido de Lino Natural';
UPDATE products SET image_url = '/products/zapatillas-recicladas.jpg' WHERE name = 'Zapatillas Recicladas';
UPDATE products SET image_url = '/products/organic-shirt.jpg' WHERE name = 'Camiseta Orgánica Básica';
UPDATE products SET image_url = '/products/sustainable-jeans.jpg' WHERE name = 'Jeans Sostenibles';
UPDATE products SET image_url = '/products/bolsas-reutilizables.jpg' WHERE name = 'Bolsas Reutilizables';
UPDATE products SET image_url = '/products/laptop-reacondicionada.jpg' WHERE name = 'Laptop Reacondicionada';
UPDATE products SET image_url = '/products/tablet-renovada.jpg' WHERE name = 'Tablet Renovada';
UPDATE products SET image_url = '/products/smartphone-reacondicionado.jpg' WHERE name = 'Smartphone Reacondicionado';
UPDATE products SET image_url = '/products/champu-solido.jpg' WHERE name = 'Champú Sólido Natural';
UPDATE products SET image_url = '/products/serum-vitamina-c.jpg' WHERE name = 'Sérum Vitamina C';
UPDATE products SET image_url = '/products/aceite-argan.jpg' WHERE name = 'Aceite de Argán Orgánico';
UPDATE products SET image_url = '/products/mascarilla-arcilla.jpg' WHERE name = 'Mascarilla Arcilla Verde';
UPDATE products SET image_url = '/products/balsamo-labial.jpg' WHERE name = 'Bálsamo Labial Vegano';
UPDATE products SET image_url = '/products/bolso-algodon.jpg' WHERE name = 'Bolso de Algodón Orgánico';
UPDATE products SET image_url = '/products/bufanda-artesanal.jpg' WHERE name = 'Bufanda Artesanal';
UPDATE products SET image_url = '/products/sombrero-paja.jpg' WHERE name = 'Sombrero de Paja Reciclada';
UPDATE products SET image_url = '/products/crema-facial.jpg' WHERE name = 'Crema Facial Orgánica';
UPDATE products SET image_url = '/products/solar-charger.jpg' WHERE name = 'Cargador Solar Portátil';
